### ISSUE TITLE
[minor] https access fails

### ISSUE THREAD

**Issue by lofidevops** [theodox/theodox.github.io#1]
Steps to reproduce:
- Enter http://theodox.github.io/about in address bar
- Hit enter
- Repeat with https://theodox.github.io/about

What should happen:
- http: page loads, with layout
- https: page loads, with layout

What happens instead:
- http: page loads, with layout (correct)
- https: page loads, layout fails (incorrect)

Notes:
- Firefox fails as described above.
- Chrome reports <a href="https://support.google.com/chrome/answer/1342714">"This page is trying to load scripts from unauthenticated sources"</a> and allows you to accept the scripts. It looks like some of the js links use http://address instead of https://address or just //address
- Just visiting the http address is not a workaround if you're running HTTPS Everywhere

**Comment by theodox** [comment]
Should be ok now, had to make all the hard coded templates https
